#include <bits/stdc++.h>
#define o using
#define oo namespace
#define ooo std
#define oooo ;
#define ooooo int
#define oooooo a
#define ooooooo b
#define oooooooo c
#define ooooooooo main
#define oooooooooo void
#define ooooooooooo (
#define oooooooooooo )
#define ooooooooooooo {
#define oooooooooooooo }
#define ooooooooooooooo ios
#define oooooooooooooooo ::
#define ooooooooooooooooo sync_with_stdio
#define oooooooooooooooooo false
#define ooooooooooooooooooo cin
#define oooooooooooooooooooo .
#define ooooooooooooooooooooo tie
#define oooooooooooooooooooooo NULL
#define ooooooooooooooooooooooo >>
#define oooooooooooooooooooooooo cout
#define ooooooooooooooooooooooooo <<
#define oooooooooooooooooooooooooo if
#define ooooooooooooooooooooooooooo -
#define oooooooooooooooooooooooooooo ==
#define ooooooooooooooooooooooooooooo 0
#define oooooooooooooooooooooooooooooo ||
#define ooooooooooooooooooooooooooooooo /
#define oooooooooooooooooooooooooooooooo else
#define ooooooooooooooooooooooooooooooooo +
#define oooooooooooooooooooooooooooooooooo return
#define ooooooooooooooooooooooooooooooooooo ,
#define oooooooooooooooooooooooooooooooooooo <
#define ooooooooooooooooooooooooooooooooooooo -1
#define oooooooooooooooooooooooooooooooooooooo 1
o oo ooo oooo
ooooo oooooo ooooooooooooooooooooooooooooooooooo
ooooooo ooooooooooooooooooooooooooooooooooo oooooooo oooo
ooooo ooooooooo ooooooooooo oooooooooo oooooooooooo ooooooooooooo
ooooooooooooooo oooooooooooooooo ooooooooooooooooo
ooooooooooo oooooooooooooooooo oooooooooooo oooo
ooooooooooooooooooo oooooooooooooooooooo ooooooooooooooooooooo
ooooooooooo oooooooooooooooooooooo oooooooooooo oooo
oooooooooooooooooooooooo oooooooooooooooooooo ooooooooooooooooooooo
ooooooooooo oooooooooooooooooooooo oooooooooooo oooo
ooooooooooooooooooo ooooooooooooooooooooooo oooooo ooooooooooooooooooooooo
ooooooo ooooooooooooooooooooooo oooooooo oooo
oooooooooooooooooooooooooo ooooooooooo oooooooo ooooooooooooooooooooooooooo
ooooooo oooooooooooooooooooooooooooo ooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooo oooooo ooooooooooooooooooooooooooooooo
ooooooooooo oooooooo ooooooooooooooooooooooooooo ooooooo oooooooooooo
oooooooooooooooooooooooooooooooooooo ooooooooooooooooooooooooooooo oooooooooooo
oooooooooooooooooooooooo ooooooooooooooooooooooooo
ooooooooooooooooooooooooooooooooooooo oooo
oooooooooooooooooooooooooooooooo oooooooooooooooooooooooo ooooooooooooooooooooooooo
oooooo ooooooooooooooooooooooooooooooo ooooooooooo
oooooooo ooooooooooooooooooooooooooo ooooooo oooooooooooo
ooooooooooooooooooooooooooooooooo oooooooooooooooooooooooooooooooooooooo oooo
oooooooooooooooooooooooooooooooooo ooooooooooooooooooooooooooooo oooo
oooooooooooooo
